### ISSUE TITLE
Deposit Upload Failed - EXANode interface

### ISSUE THREAD

**Issue by Pcolar** [dpn-admin/EXANode-Acceptance-testing#1]
https://exanode-demo.libnova.com/deposit/details/00000000000000000092

When a upload fails, the system does not recognize the failure or provide a method to resolve the error.
Status is:
The deposit is currently under an upload process or the content is awaiting for integrity verification.
Trusty Screen:
https://docs.google.com/document/d/1HFrblGX-YQ6nhCAcZbkWrv4DkheblzSdGnPqw6MLoKc/

**Comment by acarrasco-libnova** [comment]
Can you please attach the Trusty log for this upload? I'm pretty sure that it should retry when failed to upload content to the server, but it may have failed multiple times in uploading the content.

If that is the case, as Trusty cannot communicate with the server to unlock the deposit, it will remain as locked with the message: 
`The deposit is currently under an upload process or the content is awaiting for integrity verification.`

**Comment by Pcolar** [comment]
The log is on my Windows 10 server instance. I cannot access it remotely, but will upload the log file once I am able to access the machine.  This should be updated on 20180622.

**Comment by Pcolar** [comment]
[trusty_2018-06-14_17-16.log](https://github.com/dpn-admin/EXANode-Acceptance-testing/files/2134314/trusty_2018-06-14_17-16.log)

Logfile for https://exanode-demo.libnova.com/deposit/details/00000000000000000092

**Comment by Pcolar** [comment]
How can this issue be resolved?
What process/policy would DPN use for resolution with the depositor?

**Comment by Pcolar** [comment]
I was unable to recreate the original file tree on the upload device. Closing this issue as a testing failure on my part.
