### ISSUE TITLE
3.3.4.3. MBR.002.000 My Alerts (Alerts dashboard)

### ISSUE THREAD

**Issue by Pcolar** [dpn-admin/EXANode-Acceptance-testing#16]
Please demonstrate this function for each exception case:

Shows the important notifications to the user, such as:
Deposit archived
Deposit not archived
Problems with Deposits
Bulk device request
Processing or archiving problem
Audit problem

**Comment by Pcolar** [comment]
Include 3.3.3.4. MBR.002.001 Alert details for each demonstration

**Comment by Pcolar** [comment]
Please demonstrate this screen & include a link to it:
![image](https://user-images.githubusercontent.com/564971/42703354-5d5ed464-869a-11e8-8710-86117204df81.png)

**Comment by acarrasco-libnova** [comment]
The link to the notification list view is available at the top right notification icon (the bell):

![image](https://user-images.githubusercontent.com/36916975/42808034-9a04a7e8-89b2-11e8-946a-4abb8dd93a3e.png)

If you press "View all" it will lead to the notification list view.

**Comment by Pcolar** [comment]
Confirmed in 20170227 EXANODE Technical Proposal v25 Final
