### ISSUE TITLE
3.3.4.5. MBR.000.002 Main Dashboard

### ISSUE THREAD

**Issue by Pcolar** [dpn-admin/EXANode-Acceptance-testing#17]
Please demonstrate each sub-function:

![image](https://user-images.githubusercontent.com/564971/41606238-369599fe-73b1-11e8-82da-a35a9aa5819b.png)

![image](https://user-images.githubusercontent.com/564971/41606252-40a752d4-73b1-11e8-9899-3003cca82a45.png)

**Comment by Pcolar** [comment]
Submenus above are still in the technical document, but not available in the test system.

**Comment by acarrasco-libnova** [comment]
As said in the last meeting, these screenshots are outdated and have been properly updated in the last technical document.

**Comment by Pcolar** [comment]
corrected in 20170227 EXANODE Technical Proposal v25 Final
