### ISSUE TITLE
3.3.6. Data extraction and processing module

### ISSUE THREAD

**Issue by Pcolar** [dpn-admin/EXANode-Acceptance-testing#24]
Please provide a link to this documentation:

This module uses the LIBSAFE Ingestor and LIBSAFE Preprocessor modules to extract the characterization information, virus, fixity of the processed content.
Refer to the LIBSAFE technical documentation or manual for more details.

**Comment by Pcolar** [comment]
Please include a link to "LIBSAFE technical documentation or manual" to resolve this issue.

**Comment by acarrasco-libnova** [comment]
As said in the last meeting, the system technical details are defined within the specification, and it has been updated to match that, as the behavior of the modules was already defined in the specification.

In points 3.3.6, 3.3.7, 3.3.8, and 3.3.9 you have the reference for the technical details of each module.

**Comment by Pcolar** [comment]
Confirmed in 20170227 EXANODE Technical Proposal v25 Final
