### ISSUE TITLE
Create FAQ for Testy Interface

### ISSUE THREAD

**Issue by ebgore** [dpn-admin/EXANode-Acceptance-testing#26]
1) How to update your password is not intuitive - have to Edit profile and then the password option appears - need to document that for our users.

**Comment by Pcolar** [comment]
If you want a wiki page for the FAQ, it can be created here: https://github.com/dpn-admin/EXANode-Acceptance-testing/wiki

**Comment by Pcolar** [comment]
Will push a new version on Monday 7/2
