### ISSUE TITLE
Deposit of Virus payload failed - Deposit #97

### ISSUE THREAD

**Issue by Pcolar** [dpn-admin/EXANode-Acceptance-testing#27]
https://exanode-demo.libnova.com/deposit/details/00000000000000000097
2 files containing the eicar virus test payload failed to be detected. These files were detected by Windows defender on the upload machine.

https://community.f-secure.com/t5/Common-topics/Testing-your-virus-protection/ta-p/18294

[2018-06-25 22:09:15.867748] [w] [libsafeCharacterizerService.exe::__scan] Can't complete file scan: 
 [*] File:      "C:\exanode\ingestion\00000000000000000097\virus_payload.txt"
 [*] Exit code: 2
 [*] Details:   

ERROR: Could not connect to clamd on (null): Connection refused
ERROR: Could not connect to clamd on (null): Connection refused

![windows-defender-scan-97](https://user-images.githubusercontent.com/564971/41878910-295b8bb0-78a5-11e8-8ba9-c0090700e8c8.png)

**Comment by acarrasco-libnova** [comment]
The module did not fail to detect the files uploaded to the deposit, the files were not the EICAR test file.

The EICAR test file must be a 68 bytes long file containing only the exact following text:
`X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*`

As the content of the uploaded files does not match that criteria, the files were not detected:

### virus_payload.txt
```


StatusCode        : 200
StatusDescription : OK
Content           : {88, 53, 79, 33...}
RawContent        : HTTP/1.1 200 OK
                    Content-disposition: attachment; filename="eicar.com.txt"
                    Content-Length: 68
                    Cache-Control: private
                    Content-Type: application/octet-stream
                    Date: Mon, 25 Jun 2018 22:02:41 GMT
                    Ser...
Headers           : {[Content-disposition, attachment; filename="eicar.com.txt"], [Content-Length, 68], 
                    [Cache-Control, private], [Content-Type, application/octet-stream]...}
RawContentLength  : 68



```

### virus_zip_payload
```


StatusCode        : 200
StatusDescription : OK
Content           : {80, 75, 3, 4...}
RawContent        : HTTP/1.1 200 OK
                    Content-disposition: attachment; filename="eicar_com.zip"
                    Content-Length: 184
                    Cache-Control: private
                    Content-Type: application/octet-stream
                    Date: Mon, 25 Jun 2018 22:01:54 GMT
                    Se...
Headers           : {[Content-disposition, attachment; filename="eicar_com.zip"], [Content-Length, 184], 
                    [Cache-Control, private], [Content-Type, application/octet-stream]...}
RawContentLength  : 184




```

I've created a deposit with the EICAR test file and got detected as it should:
https://exanode-demo.libnova.com/deposit/details/99

The files are attached to the issue so you can see that the content does not match the EICAR test file criteria.
* [virus_payload.txt](https://github.com/dpn-admin/EXANode-Acceptance-testing/files/2136308/virus_payload.txt)
* [virus_zip_payload.zip](https://github.com/dpn-admin/EXANode-Acceptance-testing/files/2136307/virus_zip_payload.zip)

**Comment by Pcolar** [comment]
Alberto,

Thanks for checking - you are correct that the signature was not in the file. A subsequent deposit (#101) does have the virus files flagged.
