### ISSUE TITLE
3.3.3.13. MBR.006.000 User overview

### ISSUE THREAD

**Issue by Pcolar** [dpn-admin/EXANode-Acceptance-testing#29]
Verify:

1) the member administrator user is able to see a list of every user associated to the member, and access its details.

**Comment by Pcolar** [comment]
Header issue - "Yam" should be "Name"
https://exanode-demo.libnova.com/user

**Comment by Pcolar** [comment]
Also found in https://exanode-demo.libnova.com/deposit/details/ (3.3.3.8. MBR.003.002 Deposit details)

**Comment by acarrasco-libnova** [comment]
We are not able to reproduce this issue, we've even reviewed the code and there is no "Yam" string on any *.php file of the web interface, could you attach a screenshot of the issue?

**Comment by Pcolar** [comment]
Chrome is attempting to translate from Spanish:
![image](https://user-images.githubusercontent.com/564971/41924536-52055742-7938-11e8-8b6a-26cf7d1e98a0.png)

Does the base CSS identify the page language as Spanish?

**Comment by acarrasco-libnova** [comment]
I see, so the page language gets identified as Spanish. The main template <html> tag was setting the language to Spanish, so it has been changed to English:

### Before:
```
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">
```

### After:
```
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
```

We have no language references within the CSS so this should not happen again, please confirm.

**Comment by Pcolar** [comment]
Verified: 
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

**Comment by Pcolar** [comment]
html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"
