### ISSUE TITLE
EXANode shows content as ingested before confirmation from UCM/USC

### ISSUE THREAD

**Issue by Pcolar** [dpn-admin/EXANode-Acceptance-testing#3]
When depositing content, the EXANode interface sets the status as archived before content is confirmed as ingested by the UCM/USC archive.  

Further discussion is needed to determine the status at Upload, submission to UCM/USC, and confirmation of ingest into the UCM/USC system.

Example:
https://exanode-demo.libnova.com/deposit/details/00000000000000000079

Status

Deposit archive completed: 
 [*] Deposit ID:     79
 [*] Archived files: 1
 [*] Total size:     30 KB
 [*] Ellapsed time:  10ms

**Comment by wmccown** [comment]
Per our discussion today I understand it is desired that the status be set to "archiving" until the data is actually written to tape by the USC archive, at which point it will be set to "archived".  I believe at the moment this is triggered by the "completed" return from UCM which likely only indicates that the data has been written to the samfs filesystem.  

The proposal is that UCM not indicate "completed" until the data is actually written to tape, but this is likely to be difficult on the UCM side.  Also this begs the further question as to whether written to tape at USC is sufficient, or if you need to wait until it is written to tape at both locations.

**Comment by wmccown** [comment]
Jon responds as follows:

If I understand the question correctly, I believe that we already support this. That was to be the default behavior, per the specification:

Once all tape archive copies have been written to the tape archive at USC, the ingest status shall be written to the shared network file system.

Note that this does not factor in replication, only USC tape copies.

The ability to change the completion criteria to be "when the file was written to disk" was later requested by Libnova for testing purposes, and that was implemented.

The completion criteria is configured in two places:

    The configuration for the ingest folder; and
    if specified in the ingest manifest, by the <completionCriteria> element, which may be
        WHEN_WRITTEN_TO_DISK
        WHEN_ONE_ARCHIVE_COPY

The production instance default is WHEN_ONE_ARCHIVE_COPY.

The test instance had both capabilities available for their testing: https://github.com/oxsdd/ucm-dpn/issues/6

**Comment by oxsdd** [comment]
With regard to URL in the original comment above, and "deposit 79" in particular, it is unclear whether this is referring to the (shutdown) test UCM instance, or the production instance, so I checked both. There is no record of a "deposit 79" either pending ingest, or having ever been ingested in either.

**Production:** There have not been any ingests into the production UCM  instance. There are no pending ingests waiting in the UCM ingest directory. The UCM audit directory contains the weekly audit files, which indicate the empty state of the archive. The audit files are not being consumed.

**Test:** The test instance was shutdown after the production instance was configured. The metadata and archived data is still there. There is no record of receiving a deposit 79 while the test instance was running. There are no pending ingests waiting in the UCM ingest directory. There are no audits being generated and the audit directory is empty.

Considering the above, it seems that the  UCM state of deposit 79 is "not submitted for ingest".

**Comment by Pcolar** [comment]
This submission occurred on the test system, not production.  Closing and will attempt to re-create the issue in another test.
