### ISSUE TITLE
3.3.3.16. MBR.007.000 Member overview

### ISSUE THREAD

**Issue by Pcolar** [dpn-admin/EXANode-Acceptance-testing#32]
Verify:

1) Only DPN users/admins are able to access this section.
2) A list of members is shown, with the possibility to view the details for each member

**Comment by Pcolar** [comment]
When editing a member from the Member List screen, the Member Name field is truncated:

https://exanode-demo.libnova.com/member/edit/10

![image](https://user-images.githubusercontent.com/564971/41925176-cf65dc9c-7939-11e8-8de9-5f112d5f6b32.png)

![image](https://user-images.githubusercontent.com/564971/41925213-f30cd556-7939-11e8-9fa7-4317ba09cb6f.png)

**Comment by Pcolar** [comment]
This may be related to attempting to encode metadata in the member name. The JSON string is truncated.

**Comment by acarrasco-libnova** [comment]
As figured out, it was due to the usage of special characters within a form field, more specifically the double quotes `"` were truncating the value and causing the issue.

We added a filter to allow the visualization of special HTML characters in the form fields.

**Comment by Pcolar** [comment]
Validated.
