### ISSUE TITLE
3.3.4.18. MBR.007.002 New member

### ISSUE THREAD

**Issue by Pcolar** [dpn-admin/EXANode-Acceptance-testing#33]
Verify:
1) it is possible to create a new member
2) Fields: member name, member 3-digit code, member main contact name, member main contact email, member main contact phone and member total quota.
3) When it is created, the user is redirected to the MBR.007.001

**Comment by Pcolar** [comment]
1) Validated
2) After creation, Unable to edit the Member main contact name, Member main contact phone, Member main contact email
https://exanode-demo.libnova.com/member/details

![image](https://user-images.githubusercontent.com/564971/41927697-e96586b8-7940-11e8-9f2e-35cc02b2812b.png)

![image](https://user-images.githubusercontent.com/564971/41927714-f73096e8-7940-11e8-969b-4ab7e081de44.png)

**Comment by Pcolar** [comment]
Add a metadata field that will accept encoded data - future enhancement

**Comment by Pcolar** [comment]
LibNova will update the documentation of this screen

**Comment by Pcolar** [comment]
Note that the 'Member main contact phone' is cumbersome with a long list of country codes.

**Comment by acarrasco-libnova** [comment]
USA is chosen by default as the country for the contact phone input, even with more countries available, but we can restrict to USA numbers only if required.

**Comment by Pcolar** [comment]
Screen layout review needed by DPN. Is the long list of country codes cumbersome?

**Comment by Pcolar** [comment]
Validated.
