### ISSUE TITLE
3.3.4.20. MBR.009.000 Help index

### ISSUE THREAD

**Issue by Pcolar** [dpn-admin/EXANode-Acceptance-testing#35]
General information on how to use the system covering an Exanode Overview, how to manage the users and how to upload content to the node.

**Comment by Pcolar** [comment]
How is this accessed?

**Comment by Pcolar** [comment]
Some documentation is available at: https://drive.google.com/drive/folders/1U_efd7fOZaC4KxN2t6bS-phWb9PZlcDy?usp=sharing_eip&ts=5b3f4422

**Comment by acarrasco-libnova** [comment]
The documentation about the usage of the platform is included in the Usage Guide of the Exanode Web Interface, using the link available at the profile menu:

![image](https://user-images.githubusercontent.com/36916975/42836340-121ece14-89fb-11e8-8ee5-b5b1d2f8ecb8.png)

This documentation includes how to manage users (if logged in as a Member/System Administrator user), how to manage Members (if logged In as a System Adminsitrator user) and how to upload content to Exnaode.

**Comment by Pcolar** [comment]
Verified!
