### ISSUE TITLE
3.3.4.21.. MBR.010.000 Bulk upload management

### ISSUE THREAD

**Issue by Pcolar** [dpn-admin/EXANode-Acceptance-testing#36]
Verify:

1) allows to the DPN to keep track of the BTDs (Bulk Transfer Devices)
2) track every device and its status, process new requests and process BTDs.

**Comment by Pcolar** [comment]
DPN is looking for a member to assist in the testing. We would like to establish a pilot with the following major objectives:
1) Identify a volume of content to be submitted via Bulk Upload
2) Have a member request devices by creating a deposit
3) USC prepares and ships the bulk devices
4) Member receives, uploads content and returns drive to USC
5) USC receives, validates, and uploads content into EXANode
6) Content upload and ingest is verified by the member.

Physical workflow for the drives and specifications for preparation are needed.
Costs for this service should be included in the USC-DPN SLA

**Comment by oxsdd** [comment]
For the USC-side of this, please coordinate with Will Mccown, who works for USC. I am a contract software developer who works remotely from my location in Oxford, Ohio.

**Comment by Pcolar** [comment]
Waiting on DPN Pilot coordination.
