### ISSUE TITLE
3.3.4.25. MBR.012.000 Configuration

### ISSUE THREAD

**Issue by Pcolar** [dpn-admin/EXANode-Acceptance-testing#39]
Several parameters of the system can be adjusted here.

What parameters and how is this accessed?

**Comment by acarrasco-libnova** [comment]
The parameters are defined in the technical document, point 3.3.11. System settings.

The configuration area is not available as a link from the web interface, instead you need to manually change the url to "/system/settings" to access the configuration area. You need a System administrator account.

**Comment by Pcolar** [comment]
Confirmed.
