### ISSUE TITLE
Unable to recover password 

### ISSUE THREAD

**Issue by Pcolar** [dpn-admin/EXANode-Acceptance-testing#4]
https://exanode-demo.libnova.com/

When requesting a password recovery, the email is never received.

**Comment by Pcolar** [comment]
(MBR.000.001)
That will send the following email to the user:
Subject: DPN EXANODE password change request
Body:
Dear Member,
We have received a request to reset your DPN EXANODE password. If you didn’t make the request, just ignore this email. Otherwise, you can reset your password using this link.
(link for reset)
Your DPN Team.

**Comment by acarrasco-libnova** [comment]
As on the previous case (hability to change passwords on demo instance) this was disabled, but we enabled back the feature.

You should now be able to issue a password recovery request, receive the email, and reset your password to a new one using the link given on that email.

**Comment by Pcolar** [comment]
Please do not close issues until the result is validated.

**Comment by Pcolar** [comment]
Change validated - password reset via email is operational.
