### ISSUE TITLE
3.3.9.2. Time-triggered notifications

### ISSUE THREAD

**Issue by Pcolar** [dpn-admin/EXANode-Acceptance-testing#41]
Please demonstrate generation of these notifications:

3.3.9.2.1 #100 – Open deposit reminder
3.3.9.2.2 #101 – Audit information not received in time from the storage layer
3.3.9.2.3 #102 – Deposit confirmation not received on time from the storage layer

**Comment by acarrasco-libnova** [comment]
Notifications were disabled to avoid a bunch of notifications emails but were enabled again, these notifications should be triggered and received in the following days.

**Comment by Pcolar** [comment]
Transferred to Issue: https://github.com/dpn-admin/EXANode-Acceptance-testing/issues/11
