### ISSUE TITLE
Member code is editable

### ISSUE THREAD

**Issue by Pcolar** [dpn-admin/EXANode-Acceptance-testing#5]
https://exanode-demo.libnova.com/member/edit/1

After a member is created, the member code should be immutable.
The ability to change the code will affect the tracking of collections.

**Comment by acarrasco-libnova** [comment]
Removed in last update, now member codes are read-only.

**Comment by Pcolar** [comment]
I was able to modify the member code on 20180620.

**Comment by Pcolar** [comment]
This issue has been resolved.
